---
- name: BGP Initial Configuration
  hosts: junos
  collections:
    - junipernetworks.junos
  tasks:
    - name: Configure BGP Global resource.
      junos_bgp_global:
        config:
          accept_remote_nexthop: true
          add_path_display_ipv4_address: true
          advertise_from_main_vpn_tables: true
          advertise_inactive: true
          as_number: '65534'
          asdot_notation: true
          authentication_algorithm: md5
          bgp_error_tolerance:
            malformed_route_limit: 20000000
          bmp:
            monitor: true
          damping: true
          description: "Config is updated with merged operation"
          egress_te_sid_stats: true
          groups:
            - name: internal
              out_delay: 22
            - name: external
              out_delay: 20
              authentication_key: class 
          hold_time: 15
          holddown_all_stale_labels: true
          include_mp_next_hop: true
          log_updown: true
          loops: 5
          no_advertise_peer_as: true
          no_aggregator_id: true
          no_client_reflect: true
          out_delay: 20
          precision_timers: true
          preference: '3'
          keep: "all"
          mtu_discovery: True
          no_precision_timers: True
        state: merged
        
    - name: Configure BGP Global resource.
      junos_bgp_global:
        config:
          as_number: '65534'
          asdot_notation: true
          
        state: merged
