---
- name: Deletion Operation
  hosts: junos
  collections:
    - junipernetworks.junos
  
  tasks:
    # - name: Delete all the exiting routing-instances in running config
    #   junos_routing_instances:
    #     config:
    #     state: deleted
    - name: Delete specific routing-instance in running config
      junos_routing_instances:
        config:
          - name: forwardinst
        state: deleted