---
- name: BGP Address Family Configuration
  hosts: junos
  collections:
    - junipernetworks.junos
  
  tasks:
    - name: Configure basic config relevant to BGP GLOBAL
      junos_config:
        lines:
          - set protocols bgp group internal out-delay 12
          - set routing-options autonomous-system 65534
          - set routing-options autonomous-system loops 3
          - set routing-options autonomous-system asdot-notation
          - set protocols bgp accept-remote-nexthop
          - set protocols bgp add-path-display-ipv4-address
          - set protocols bgp advertise-from-main-vpn-tables
          - set protocols bgp advertise-inactive
          - set protocols bgp authentication-algorithm md5
          - set protocols bgp bgp-error-tolerance malformed-route-limit 20000000
          - set protocols bgp bmp monitor enable
          - set protocols bgp damping
          - set protocols bgp description "This is configured with Junos_bgp resource module"
          - set protocols bgp egress-te-sid-stats
          - set protocols bgp hold-time 5
          - set protocols bgp holddown-all-stale-labels
          - set protocols bgp include-mp-next-hop
          - set protocols bgp log-updown
          - set protocols bgp no-advertise-peer-as
          - set protocols bgp no-aggregator-id
          - set protocols bgp no-client-reflect
          - set protocols bgp out-delay 10
          - set protocols bgp precision-timers
          - set protocols bgp preference 2

    - name: Merge bgp address family resource config
      junos_bgp_address_family:
        config:
          address_family:
            - afi: 'evpn'
              af_type:
                - type: 'signaling'
                  accepted_prefix_limit:
                    maximum: 20
                    limit_threshold: 98
                    idle_timeout_value: 2001
                  damping: true
                  defer_initial_multipath_build:
                    maximum_delay: 2
            - afi: 'inet'
              af_type:
                - type: 'flow'
                  legacy_redirect_ip_action:
                    send: true
                    receive: true
                  loops: 4
                  no_install: true
                  output_queue_priority_expedited: true
                  secondary_independent_resolution: true

                - type: 'unicast'
                  extended_nexthop: true
                  extended_nexthop_color: true
                  local_ipv4_address: '9.9.9.9'

                - type: 'labeled-unicast'
                  entropy_label:
                    no_next_hop_validation: true
                  explicit_null:
                    connected_only: true
                  per_prefix_label: true
                  per_group_label: true
                  prefix_limit:
                    maximum: 20
                    limit_threshold: 99
                    forever: true
                  resolve_vpn: true
                  rib: 'inet.3'
                  route_refresh_priority_expedited: true
                  route_refresh_priority_priority: 3

                - type: 'any'
                  accepted_prefix_limit:
                    maximum: 20
                    limit_threshold: 99
                    idle_timeout_value: 2000
                  damping: true
                  defer_initial_multipath_build:
                    maximum_delay: 2
                  delay_route_advertisements:
                    max_delay_route_age: 20
                    max_delay_routing_uptime: 32000
                    min_delay_inbound_convergence: 32000
                    min_delay_routing_uptime: 23000
                  graceful_restart_forwarding_state_bit: 'from-fib'

