
Important links:

Understand how netconf delete workd at attribute level:
    - https://www.juniper.net/documentation/us/en/software/junos/netconf/topics/task/netconf-configuration-elements-deleting.html#:~:text=In%20a%20NETCONF%20session%20with,XML%20protocol

Example: Virtual Routing and Forwarding (VRF) and Service Configuration
    - https://www.juniper.net/documentation/en_US/junos/topics/example/vpn-routing-forwarding-vrf-service-configuring.html

How to Run Ansible Integration Tests:
  - ansible-test network-integration --inventory test-inventory junos_routing_instances -vvv

NETCONF CLI EXECUTION:
  - How to connect with Netconf:
      - ssh -i /home/rothakur/.vagrant.d/insecure_private_key -p 830 vagrant@192.168.122.101 -s netconf
  - Capabilities:
      <hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
        <capabilities>
          <capability>urn:ietf:params:netconf:base:1.0</capability>
          <capability>urn:ietf:params:netconf:capability:candidate:1.0</capability>
          <capability>urn:ietf:params:netconf:capability:confirmed-commit:1.0</capability>
          <capability>urn:ietf:params:netconf:capability:validate:1.0</capability>
          <capability>urn:ietf:params:netconf:capability:url:1.0?scheme=http,ftp,file</capability>
          <capability>urn:ietf:params:xml:ns:netconf:base:1.0</capability>
          <capability>urn:ietf:params:xml:ns:netconf:capability:candidate:1.0</capability>
          <capability>urn:ietf:params:xml:ns:netconf:capability:confirmed-commit:1.0</capability>
          <capability>urn:ietf:params:xml:ns:netconf:capability:validate:1.0</capability>
          <capability>urn:ietf:params:xml:ns:netconf:capability:url:1.0?protocol=http,ftp,file</capability>
          <capability>urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring</capability>
          <capability>http://xml.juniper.net/netconf/junos/1.0</capability>
          <capability>http://xml.juniper.net/dmi/system/1.0</capability>
        </capabilities>
      </hello>
      ]]>]]>
  
  - RPC message get:
      <rpc>
      <get [format=" xml)"]>
      </get>
      </rpc>
      ]]>]]>

   




[TODO]
- egress_protection
- routing-interface


set policy-options policy-statement test-policy term t1 then reject
set policy-options policy-statement test-policy-1 term t1 then reject

set routing-instances test interface sp-0/0/0.0
set routing-instances test interface gr-0/0/0.0 

set routing-instances test instance-type vrf
set routing-instances test route-distinguisher 10.58.255.1:37
set routing-instances test vrf-import test-policy
set routing-instances test vrf-export test-policy
set routing-instances test vrf-export test-policy-1

set routing-instances test connector-id-advertise

set routing-instances vtest1 instance-type virtual-router
set routing-instances vtest2 instance-type virtual-router
