---
- name: BGP Unit Test Task
  hosts: junos
  collections:
    - junipernetworks.junos
  tasks:
    - name: Configure BGP Global resource.
      junos_bgp_global:
        config:
          accept_remote_nexthop: true
          advertise_from_main_vpn_tables: true
          advertise_inactive: true
          as_number: '65534'
          authentication_algorithm: md5
          keychain: "junos"
          bgp_error_tolerance:
            malformed_route_limit: 30000000
          damping: true
          description: "This is configured with Junos_bgp resource module"
          hold_time: 5
          holddown_all_stale_labels: true
          log_updown: true
          no_advertise_peer_as: true
          no_aggregator_id: true
          out_delay: 10
          preference: '2'
        state: merged
    
