---
- name: BGP Replaced Unit Test Task
  hosts: junos
  collections:
    - junipernetworks.junos
  tasks:
    - name: Replace running-config BGP global configuration with provided configuration.
      junos_bgp_global:
        config:
          accept_remote_nexthop: true
          advertise_from_main_vpn_tables: true
          advertise_inactive: true
          as_number: '65534'
          authentication_algorithm: md5
          bgp_error_tolerance:
            malformed_route_limit: 20000000
          damping: true
          description: "This is configured with Junos_bgp resource module"
          groups:
            - name: internal
              out_delay: 22
            - name: external
              out_delay: 20
          hold_time: 4
          holddown_all_stale_labels: true
          log_updown: true
          keep: "all"
          mtu_discovery: True
          no_precision_timers: True
          no_advertise_peer_as: true
          no_aggregator_id: true
          out_delay: 10
          preference: '2'
        state: replaced